### ISSUE TITLE
Question on the Beaver's generation

### ISSUE THREAD

**Issue by fionser** [LucasFenaux/PILLAR-ESPN#1]
Doest ESPN uses any two-party protocol to generate the Beaver triple ?
Or just re-use CrypTen's TTP/TFP provider for the beaver generation ?

**Comment by LucasFenaux** [comment]
We do re-use CrypTen's TTP/TFP provider for the beaver generation. You can find additional details in the [paper](https://arxiv.org/abs/2306.08538). 

I am closing this issue as the question has been answered.

**Comment by fionser** [comment]
I mean, if a TTP/TFP is used, then it might be unfair to directly compare with COINN, GForce et al. which are helper-less.

**Comment by LucasFenaux** [comment]
The TTP is only used in the pre-computation phase and we do not benchmark this part for any of the protocols. We only measure online time.
